#+TITLE: Composition Lesson #1
#+AUTHOR: Aleksandr Yakunichev
#+EMAIL: hi@ya.codes

* Ключевые понятия урока
1. В начале музыка по сути одноголосна (Гомофония, Григорианский хорал);
2. Первые опыты нотации (Леонин, Перотин), зарождается полифония;
3. Полифония, голоса становятся более самостоятельными, появляются специфические полифонические формы в музыке, например, форма Фуги (это мы разберем подробно в следующий раз);
4. Далее наступает гармоническая реформа классицизма (Гайдн, Моцарт, Бетховен), образуются гармонические иерархии (Тоника, Доминанта, Субдоминанта), с помощью этой иерархии гармоний выстраивается форма целого произведения (Симфонии, Сонаты).
     
Описывая так называемую старинную музыку (например, многоголосие XV—XVI веков), «гомофонией» также называют моноритмическую (у англоязычных homorhythmic, «гоморитмическая») фактуру, то есть такую, в которой каждый голос многоголосного целого движется в одном и том же или весьма подобном ритме.

* Ссылки
  - [[https://soundtimes.ru/uroki-muzyki/polifoniya][Что такое полифония: определение, история, виды, жанры, композиторы]] 
  - [[http://os.colta.ru/music_classic/events/details/32547/?expand=yes#expand][Владимир Мартынов: тональность и модальность]] 
* Задание
** TODO [[file:2020-08-04/%D0%91%D0%B0%D1%85%20-%20%D0%9C%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%D0%BA%D0%B0%D1%8F%20%D0%B4%D0%B2%D1%83%D1%85%D0%B3%D0%BE%D0%BB%D0%BE%D1%81%D0%BD%D0%B0%D1%8F%20%D1%84%D1%83%D0%B3%D0%B0.pdf][Бах - Маленькая двухголосная фуга]]
   Определить как строится тема, какие формы развития, есть ли дробление, замыкание?
** TODO Бетховен - 1 соната, 1 часть
   Определить где главная партия, как она построена.
   Факультативное задание - найти побочную партию. Она в данном случае будет в тональности Доминанты к ля-бемоль мажору - это параллельная тональность для фа-минора.
* Вопросы
** [[https://soundtimes.ru/uroki-muzyki/polifoniya][Что такое полифония: определение, история, виды, жанры, композиторы]]
   - [[https://youtu.be/IqcBr7GO7oY][Модальность]], модальный лад.
   - [[https://ludustonalis.jimdofree.com/%25D0%25BF%25D0%25BE%25D0%25BB%25D0%25B8%25D1%2584%25D0%25BE%25D0%25BD%25D0%25B8%25D1%258F/%25D0%25BA%25D0%25BE%25D0%25BD%25D1%2582%25D1%2580%25D0%25B0%25D0%25BF%25D1%2583%25D0%25BD%25D0%25BA%25D1%2582-%25D0%25BF%25D1%2580%25D0%25BE%25D1%2581%25D1%2582%25D0%25BE%25D0%25B9-%25D0%25B8-%25D1%2581%25D0%25BB%25D0%25BE%25D0%25B6%25D0%25BD%25D1%258B%25D0%25B9/][Контрапункт]]. Простой, сложный, вертикально, горизонтально, вдвойне подвижной.
   - Разобрать правила полифонии в строгом стиле: хроматизмы встречаются редко и на большом расстоянии, что такое скачки.
   - Разобрать техники соединения мелодий с другими голосами: подголосочный метод, имитация.
   - Разобрать органум, мотет и мадригал.
   - Разобрать противосложение-контрапункт и интермеди в свободном стиле полифонии.
   - Разобрать фугу, сюиту и чакону.
** [[http://os.colta.ru/music_classic/events/details/32547/?expand=yes#expand][Владимир Мартынов: тональность и модальность]]
   - Разобрать сонтантную форму.
* Термины
** Вводный тон
   Неустойчивый звук лада, расположенный на секунду ниже или выше I ступени и тяготеющий к ней. Звук VII ступени, как прилегающий к I ступени снизу, называется нижним В. т.; звук II ступени - соответственно верхним. 
** Контрапункт
   Одновременное сочетание двух и более мелодий в разных голосах. *Простым контрапунктом* называется соединение мелодий, звучащее только один раз. Если при повторном проведении происходят какие-либо изменения в самих мелодиях или в их соотношении относительно друг друга, то *такой контрапункт будет называться сложным*.
** Канон
   Полифоническая форма, в которой мелодия образует контрапункт сама с собой. Основной технико-композиционный приём, положенный в основу канона, называется (канонической) имитацией.
** Монодия
   Одноголосное пение или игра на одноголосном инструменте.
